export const menuList = [
  { id: "1", menuItemLink: "/", menuItemName: "Главное" },
  {
    id: "2",
    menuItemLink: "/mytracks",
    menuItemName: "Мой плейлист",
  },
  { id: "3", menuItemLink: "/login", menuItemName: "Войти" },
];

export const pageNames = [
  { id: "1", menuItemLink: "/playlist-day", pageName: "Плейлист дня" },
  { id: "2", menuItemLink: "/hits", pageName: "100 хитов" },
  { id: "3", menuItemLink: "/indi", pageName: "Инди-заряд" },
];

export const tracks = [
  {
    id: 1,
    title: "Guilt",
    link: "#",
    span: "",
    author: "Nero",
    album: "Welcome Reality",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "4:44",
    year: "1969",
    genre: "",
  },
  {
    id: 2,
    title: "Elektro",
    link: "#",
    span: "",
    author: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "2:22",
    year: "1970",
    genre: "rock",
  },
  {
    id: 3,
    title: "I’m Fire",
    link: "#",
    span: "",
    author: "Ali Bakgor",
    album: "I’m Fire",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "2:22",
    year: "1980",
    genre: "techno",
  },
  {
    id: 4,
    title: "Non Stop",
    link: "#",
    span: "(Remix)",
    author: "Стоункат, Psychopath",
    album: "Non Stop",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "4:12",
    year: "1975",
    genre: "",
  },
  {
    id: 5,
    title: "Run Run",
    link: "#",
    span: "",
    author: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "2:54",
    year: "1965",
    genre: "",
  },
  {
    id: 6,
    title: "Eyes on Fire",
    link: "#",
    span: "(Zeds Dead Remix)",
    author: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "5:20",
    year: "1971",
    genre: "",
  },
  {
    id: 7,
    title: "Mucho Bien",
    link: "#",
    span: "(Hi Profile Remix)",
    author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "3:41",
    year: "",
    genre: "",
  },
  {
    id: 8,
    title: "Knives n Cherries",
    link: "#",
    span: "",
    author: "minthaze",
    album: "Captivating",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "1:48",
    year: "",
    genre: "",
  },
  {
    id: 9,
    title: "How Deep Is Your Love",
    link: "#",
    span: "",
    author: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "3:32",
    year: "",
    genre: "",
  },
  {
    id: 10,
    title: "Morena",
    link: "#",
    span: "",
    author: "Tom Boxer",
    album: "Soundz Made in Romania",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "3:36",
    year: "",
    genre: "",
  },
  {
    id: 11,
    title: "",
    link: "",
    span: "",
    author: "",
    album: "",
    iconLinkNote: "/img/icon/sprite.svg#icon-note",
    iconLinkLike: "/img/icon/sprite.svg#icon-like",
    trackTime: "3:36",
    year: "",
    genre: "",
  },
  {
    id: 12,
    title: "",
    link: "",
    span: "",
    author: "",
    album: "",
    iconLinkNote: "",
    iconLinkLike: "",
    trackTime: "",
    year: "",
    genre: "",
  },
  {
    id: 13,
    title: "",
    link: "",
    span: "",
    author: "",
    album: "",
    iconLinkNote: "",
    iconLinkLike: "",
    trackTime: "",
    year: "",
    genre: "",
  },
  {
    id: 14,
    title: "",
    link: "",
    span: "",
    author: "",
    album: "",
    iconLinkNote: "",
    iconLinkLike: "",
    trackTime: "",
    year: "",
    genre: "",
  },
  {
    id: 15,
    title: "",
    link: "",
    span: "",
    author: "",
    album: "",
    iconLinkNote: "",
    iconLinkLike: "",
    trackTime: "",
    year: "",
    genre: "",
  },
  {
    id: "",
    title: "",
    link: "",
    span: "",
    author: "",
    album: "",
    iconLinkNote: "",
    iconLinkLike: "",
    trackTime: "",
    year: "",
    genre: "",
  },
];

export const trackPlay = {
  author: "Ты та",
  album: "Баста",
};
